.\" Manpage for vs
.\" Report errors or typos to https://github.com/frc1418/vs
.TH vs 7 "22 Aug 2017" "1.0.0" "vs man page"

.SH NAME
vs \- CLI tool for easy manipulation of FRC scouting data

.SH SYNOPSIS
.B vs
[\fIOPTION\fR]...
.TP
Where \fIOPTION\fR represents what you want to do with your data. Valid options include cons(olidate) for consolidating multiple datasets, conf(licts) for eliminating duplicate and conflicting data, and csv/ss/spreasheet for converting JSON data into a CSV document.

.SH DESCRIPTION
vs is a data analysis suite for manipulation of FRC scouting data. It was originally designed for VictiScout data, but also works with XScout's and any other JSON-formatted scouting data.

.SH BUGS
Please see current issues on
.UR https\://\:github.com/frc1418/vs/issues
issue tracker
.UE ,
and report any bugs or request features you'd like.

.SH AUTHORS
This software is maintained by
.MT robotics1418@\:gmail.com
FIRST Robotics Competition Team 1418
.ME
since 2016 on
.UR https\://\:github.com/frc1418/vs
GitHub
.UE .
This manual page was written by
.MT me@\:erikboesen.com
Erik Boesen
.ME .
